### ISSUE TITLE
Error while building apk

### ISSUE THREAD

**Issue by incrypt0** [davigmacode/flutter_smart_select#29] opened 2020-10-12 13:45 UTC
Iam getting this error when building apk when using this package

```
lutter build apk --target-platform=android-arm
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///home/incrypto/flutter/.pub-cache/hosted/pub.dartlang.org/smart_select-4.2.0/lib/src/choices_empty.dart:17:15
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/incrypto/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 896
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/home/incrypto/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 42s              

```

But when i pass the --no--tree-shake-icons flag to flutter build apk it works perfectly . Is this the inteneded behaviour?

**Comment by davigmacode** [comment] 2020-10-13 09:46
Duplicate of #24

**Closed by davigmacode** 2020-10-13 09:46 UTC

**Comment by vasilich6107** [comment] 2021-11-12 23:11
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
